version: '2'
services:

    php:
        build:
          dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
          context: 'docker/php'
          args:
            - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
        image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
        environment:
          - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
          - PHP_ENABLE_XDEBUG
          - TEST_RUNTIME_PATH=/tmp/runtime
        volumes:
          #- ./tests:/tests:delegated
          # Framework testing
          #- ./_host-volumes/yii2:/yii2:delegated
          # Application testing
          - ./app:/app:delegated
          # Composer cache
          - ~/.composer-docker/cache:/root/.composer/cache:delegated

    db:
        image: mysql:5.7
        volumes:
            - /var/lib/mysql
            - ./docker/mysql/config/cnf:/etc/mysql/conf.d/config.conf
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: aulas
            MYSQL_USER: aulas_user
            MYSQL_PASSWORD: aulas_pass
